config/routes.rb
Throneofthestars::Application.routes.draw do

  match '' => 'home#index', :as => :root
  match 'empire' => 'empire#index', :as => :empire
  match 'church' => 'church#index', :as => :church
  match 'announcements' => 'empire#announcements', :as => :announcements
  match 'login' => 'player_sessions#new', :as => :login
  match 'logout' => 'player_sessions#destroy', :as => :logout
  match 'password_reset' => 'password_resets#new', :as => :password_reset
  match 'password_reset/:id' => 'password_resets#edit', :as => :edit_password
  match 'confirm/:id' => 'players#confirm', :as => :confirm
  match 'House/:name' => 'noble_houses#show'
  match 'Planet/:name' => 'worlds#show'
  match 'Planet/:world/:name' => 'regions#show'
  match 'Item/:name' => 'items#show'
  match 'BuildingType/:name' => 'building_types#show'
  match 'ShipType/:name' => 'starship_types#show'
  match 'Character/:guid' => 'characters#show'
  match 'Starship/:guid' => 'starships#show'
  match 'Army/:guid' => 'armies#show'
  match 'Army/:guid/units/:id' => 'units#show'
  match 'Army/:guid/units/:id/edit' => 'units#edit'
  match 'Estate/:guid' => 'estates#show'
  match 'Character/:guid/promote' => 'characters#promote'
  match 'json/world_regions/:id' => 'json#world_regions'
  match 'json/region_estates/:id' => 'json#region_estates'
  match 'json/house_characters/:id' => 'json#house_characters'
  match 'json/single_females/:id' => 'json#single_females'
  match 'json/single_males/:id' => 'json#single_males'
  match 'json/army_units/:id' => 'json#army_units'
  match 'messages/preview' => 'messages#preview'
  match 'Message/:guid' => 'messages#show'
  match 'unsubscribe/:guid' => 'players#unsubscribe'
  match 'orders/:id/up' => 'orders#up'
  match 'orders/:id/down' => 'orders#down'
  match 'orders/:id/cancel' => 'orders#destroy'
  match 'admin' => 'admin#index'
  match 'admin/players' => 'admin#players'
  match 'admin/spawner' => 'admin#spawner'
  match 'admin/reported' => 'admin#reported'
  match 'admin/newsletter' => 'admin#newsletter'

  resources :starship_configurations
  resources :starship_configuration_items
  resources :units
  resources :armies
  resources :starships
  resources :starship_types
  resources :buildings
  resources :estates
  resources :characters
  resources :orders
  resources :messages
  resources :noble_houses
  resources :regions
  resources :items
  resources :worlds
  resources :building_types
  resources :player_sessions
  resources :players
  resources :image_files

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html, :js

  def index
  	@version = true
    @home = true
    current_player.read_news! if current_player && tab?(:news)
  	if current_player && !current_player.signup_complete?
      redirect_to new_noble_house_path
      return
    end
    unless cached?
    	@news = current_noble_house ? News.home_news(current_noble_house) : News.empire_and_church
    end
  end
end

app/views/home/_introduction.html.erb
<p>
  One Thousand Years Ago, the <%=link_to "Empire of Man", empire_path %> crumbled into civil war as the great <%=link_to "Noble Houses", noble_houses_path %> pitted their fearsome war machines against each other.
</p>
<p>
  Nuclear devastation soon followed and the worlds regressed into barbarism with only the great archives of <%=link_to "the Church", church_path %> left intact in their impregnable fortresses.
</p>
<p>
  Yet some survived the apocalypse that came, with a few ancient houses holding on to the old traditions. They have inspired the new would-be nobility to rise out of the savage landscape and forge their own powerbases.
</p>
<p>
  Today, civilisation is being rebuilt and once more powerful men lay claim to the heritage of the old Empire.
  The Church slowly opens its door to the people again and carefully shares some of its many secrets with the aspiring nobility.
</p>
<%
estate_link = link_to "Estate", new_player_path
  house_link = link_to "your Noble House", new_player_path
  starships_link = link_to "two starships", new_player_path
  character_link = link_to "characters", new_player_path
%>
<p>
  You take the role of a Baron of a new House seeking power, fortune and glory amongst the <%=link_to "Twelve Worlds", worlds_path %>. Your House is the lucky recipient of assistance from the Church which spurs you on to restore the Holy Empire to its former glory.
  They encourage you to act wisely and pay tithes so you will be known for your piety with the One True God. In return, much of the lost lore can be restored.
</p>
<p>
  Your modest <%=estate_link%> has received a flood of workers and <%=house_link%> has been given the boost of <%=starships_link%> and a mandate to fulfil the destiny of Mankind and reunite the Empire.
</p>
<p>
  Through careful use of <%=character_link%>, both major and minor, you can command vast estates, huge armies and mighty starships to do your bidding.
</p>
<p>
  Take part in the devilish intrigue and diplomacy of the Noble Houses; feast at lavish weddings and take part in spirited tournaments,
  fight for supremacy through military conquest or become wealthy as a crafty trader but do not neglect to manage your own household!
</p>
<p>
  In <span class="title">Throne of the Stars</span>, the only way to lose is to end up with no heir to carry on your legacy. With carefully arranged marriages, your children will be the most valuable assets you have at your disposal.
</p>

app/views/home/_tabs.html.erb
<% unless current_noble_house %>
	<%=tab(:introduction, true) do -%>
	<div id="introduction" class="tab">
	<%=render :partial => 'introduction' %>
	</div>
	<% end -%>
<% else %>
	<%=tab(:welcome, true) do -%>
	<div id="welcome" class="tab">
	<%=render :partial => 'welcome' %>
	</div>
	<% end -%>
<% end %>

<%=tab(:news) do -%>
<div id="news" class="tab">
<%=render :partial => '/news/list', :locals => {:news => @news, :highlight_public_news => true} %>
</div>
<% end -%>

<%=tab(:events) do -%>
<div id="events" class="tab">
<%=render :partial => '/events/list', :locals => {:events => Events.all_pending_or_now} %>
</div>
<% end -%>

app/views/home/_welcome.html.erb
<% 
	message_from = current_noble_house.chancellor
	message_from = current_noble_house.home_estate.steward unless message_from
	message_from = current_noble_house.characters.first unless message_from
	wife = current_baron.spouse
	request_from = wife && wife.id != message_from.id ? "Your beloved #{wife.display_name} has" : "The good Barons of the realm have"
%>
<p>
<%=current_baron.salutation%>, 
</p>
<p>
	As the most worthy ruler of <%=link_to_house(current_noble_house)%> you may wish to review your <%=link_to("estate holdings", estates_path)%>, your <%=link_to("glorious armies", armies_path)%> or your <%=link_to("mighty starships", starships_path)%>.
</p>
<p>
	The <%=link_to("members of your House", characters_path)%> await your instructions.
</p>
<p>
	As your humble servant I have prepared a small document which I hope you <%=link_to("may take the time to read", "http://throneofthestars.wikia.com/wiki/Tutorial", :target => 'help')%>. 
</p>
<p>
	Please forgive me for any impertinance in suggesting you have need of my advice! You are of course knowledgable beyond measure <%=link_to('in the ways of the world',$WIKI_HOME, :target => 'help')%>.
</p>
<p>
	<%=request_from%> reminded me to mention the upcoming <%=link_to('society gathering',$FORUM_HOME, :target => 'forums')%> so all may be elevated by your presence. 
</p>
<p>
	I will take no further time from your busy schedule.
</p>
<p>
	Your humble servant,
</p>
<p>
	<%=link_to_character(message_from)%>
</p>

app/views/home/index.html.erb
<% title "Throne of the Stars" %>
<% 
if current_noble_house
	tabbed_menu({:welcome => 'Welcome', :news => 'Latest News', :events => 'Upcoming Social Events'},[link_to("Announcements", announcements_path), link_to_own_house,link_to("Characters", characters_path),link_to("Estates", estates_path),link_to("Armies", armies_path),link_to("Starships", starships_path),link_to("Messages", messages_path)])
else
	tabbed_menu({:introduction => 'Introduction', :news => 'Latest News', :events => 'Upcoming Social Events'},[link_to("Announcements", announcements_path), link_to("The Empire", empire_path),link_to("The Church", church_path),link_to("Noble Houses", noble_houses_path),link_to("Solar System", worlds_path),link_to("Databank", items_path)])
end
%>

<%=render :partial => 'tabs'%>

app/views/home/index.js.erb
<%=js_tab(render :partial => 'tabs')%>