config/routes.rb
Throneofthestars::Application.routes.draw do

  match '' => 'home#index', :as => :root
  match 'empire' => 'empire#index', :as => :empire
  match 'church' => 'church#index', :as => :church
  match 'announcements' => 'empire#announcements', :as => :announcements
  match 'login' => 'player_sessions#new', :as => :login
  match 'logout' => 'player_sessions#destroy', :as => :logout
  match 'password_reset' => 'password_resets#new', :as => :password_reset
  match 'password_reset/:id' => 'password_resets#edit', :as => :edit_password
  match 'confirm/:id' => 'players#confirm', :as => :confirm
  match 'House/:name' => 'noble_houses#show'
  match 'Planet/:name' => 'worlds#show'
  match 'Planet/:world/:name' => 'regions#show'
  match 'Item/:name' => 'items#show'
  match 'BuildingType/:name' => 'building_types#show'
  match 'ShipType/:name' => 'starship_types#show'
  match 'Character/:guid' => 'characters#show'
  match 'Starship/:guid' => 'starships#show'
  match 'Army/:guid' => 'armies#show'
  match 'Army/:guid/units/:id' => 'units#show'
  match 'Army/:guid/units/:id/edit' => 'units#edit'
  match 'Estate/:guid' => 'estates#show'
  match 'Character/:guid/promote' => 'characters#promote'
  match 'json/world_regions/:id' => 'json#world_regions'
  match 'json/region_estates/:id' => 'json#region_estates'
  match 'json/house_characters/:id' => 'json#house_characters'
  match 'json/single_females/:id' => 'json#single_females'
  match 'json/single_males/:id' => 'json#single_males'
  match 'json/army_units/:id' => 'json#army_units'
  match 'messages/preview' => 'messages#preview'
  match 'Message/:guid' => 'messages#show'
  match 'unsubscribe/:guid' => 'players#unsubscribe'
  match 'orders/:id/up' => 'orders#up'
  match 'orders/:id/down' => 'orders#down'
  match 'orders/:id/cancel' => 'orders#destroy'
  match 'admin' => 'admin#index'
  match 'admin/players' => 'admin#players'
  match 'admin/spawner' => 'admin#spawner'
  match 'admin/reported' => 'admin#reported'
  match 'admin/newsletter' => 'admin#newsletter'

  resources :starship_configurations
  resources :starship_configuration_items
  resources :units
  resources :armies
  resources :starships
  resources :starship_types
  resources :buildings
  resources :estates
  resources :characters
  resources :orders
  resources :messages
  resources :noble_houses
  resources :regions
  resources :items
  resources :worlds
  resources :building_types
  resources :player_sessions
  resources :players
  resources :image_files

end

app/controllers/building_types_controller.rb
class BuildingTypesController < ApplicationController
  def index
    @databank = true
    @building_types = BuildingType.paginate(:page => params[:page]).order('id ASC') unless cached?
  end

  def show
    @databank = true
    @building_type = nil
    if params[:name]
      @building_type = BuildingType.find_by_category(params[:name])
    elsif params[:id]
      @building_type = BuildingType.find(params[:id])
    else
      redirect_to :action => :index
    end
    render :layout => 'static' unless @building_type.nil? || params[:static].blank?
  end

  def cache_model
    @building_type || super
  end
end

app/helpers/building_types_helper.rb
module BuildingTypesHelper
  def link_to_building_type(building_type,static=false)
  	if static
    	link_to building_type.category, "/BuildingType/#{building_type.category}?static=true", :rel => 'lightbox', :title => building_type.category
    else
    	link_to building_type.category, "/BuildingType/#{building_type.category}"
    end
  end

  def options_for_building_types(selected)
    list = BuildingType.all
    id = selected.nil? ? 0 : selected.to_i
    options_from_collection_for_select(list,"id","category",id)
  end
end

app/views/building_types/index.html.erb
<% title "Databank : Building Types" %>

<%=tab(:index, true) do-%>
  <table width="100%">
    <tr>
      <th>Type</th>
      <th>Workers*</th>
      <th>Function</th>
      <th>Raw Materials*</th>
    </tr>
    <% for building_type in @building_types %>
      <tr>
        <td><%=link_to_building_type building_type %></td>
        <td><%=h building_type.workers_needed %> x <%=h building_type.worker_type %></td>
        <td><%=h building_type.building_function %></td>
        <td>
          <ul>
            <% building_type.raw_materials.each do |ib| -%>
            <li><%=link_to_item ib.item, ib.quantity%></li>
            <% end -%>
          </ul>
        </td>
      </tr>
    <% end %>
  </table>
  <p style="color: #fff">
    * per level
  </p>
  <div class="pagination">
    <%= will_paginate @building_types %>
  </div>
<% end %>

app/views/building_types/show.html.erb
<% title "Building : #{@building_type.category}" %>
<%
tabbed_menu({:data => @building_type.category},[link_to('Other Buildings', building_types_path)])
%>
<%=tab(:data, true) do -%>
<div id="building-type" class="tab">
  <table>
  <tr>
    <th colspan="2"><%=h @building_type.building_function %></th>
  </tr>

  <tr>
    <th>Workers Needed per level:</th>
    <td><%=h @building_type.workers_needed %> x <%=h @building_type.worker_type %></td>
  </tr>

  <% if @building_type.item_produced %>
  <tr>
    <th>Item Produced:</th>
    <td><% if @building_type.item_produced_quantity > 0 %><%=@building_type.item_produced_quantity%> x <% end %>
    <%=link_to_item  @building_type.item_produced %></td>
  </tr>
  <% end  %>

  <% unless @building_type.trade_good_type.blank? %>
  <tr>
    <th>Trade Goods Produced:</th>
    <td><%=h @building_type.trade_good_type %></td>
  </tr>
  <% end  %>

  <% unless @building_type.recruitment_type.blank? %>
  <tr>
    <th>Workers Recruited:</th>
    <td><%=h @building_type.recruitment_type %></td>
  </tr>
  <% end  %>

  <% if @building_type.has_raw_materials? %>
  <tr>
    <th>Raw Materials:</th>
    <td><ul>
      <% @building_type.raw_materials.each do |ib| -%>
      <li><%=link_to_item ib.item, ib.quantity%></li>
      <% end -%>
    </ul></td>
  </tr>
  <% end %>
  </table>
</div>
<% end %>