config/routes.rb
Throneofthestars::Application.routes.draw do

  match '' => 'home#index', :as => :root
  match 'empire' => 'empire#index', :as => :empire
  match 'church' => 'church#index', :as => :church
  match 'announcements' => 'empire#announcements', :as => :announcements
  match 'login' => 'player_sessions#new', :as => :login
  match 'logout' => 'player_sessions#destroy', :as => :logout
  match 'password_reset' => 'password_resets#new', :as => :password_reset
  match 'password_reset/:id' => 'password_resets#edit', :as => :edit_password
  match 'confirm/:id' => 'players#confirm', :as => :confirm
  match 'House/:name' => 'noble_houses#show'
  match 'Planet/:name' => 'worlds#show'
  match 'Planet/:world/:name' => 'regions#show'
  match 'Item/:name' => 'items#show'
  match 'BuildingType/:name' => 'building_types#show'
  match 'ShipType/:name' => 'starship_types#show'
  match 'Character/:guid' => 'characters#show'
  match 'Starship/:guid' => 'starships#show'
  match 'Army/:guid' => 'armies#show'
  match 'Army/:guid/units/:id' => 'units#show'
  match 'Army/:guid/units/:id/edit' => 'units#edit'
  match 'Estate/:guid' => 'estates#show'
  match 'Character/:guid/promote' => 'characters#promote'
  match 'json/world_regions/:id' => 'json#world_regions'
  match 'json/region_estates/:id' => 'json#region_estates'
  match 'json/house_characters/:id' => 'json#house_characters'
  match 'json/single_females/:id' => 'json#single_females'
  match 'json/single_males/:id' => 'json#single_males'
  match 'json/army_units/:id' => 'json#army_units'
  match 'messages/preview' => 'messages#preview'
  match 'Message/:guid' => 'messages#show'
  match 'unsubscribe/:guid' => 'players#unsubscribe'
  match 'orders/:id/up' => 'orders#up'
  match 'orders/:id/down' => 'orders#down'
  match 'orders/:id/cancel' => 'orders#destroy'
  match 'admin' => 'admin#index'
  match 'admin/players' => 'admin#players'
  match 'admin/spawner' => 'admin#spawner'
  match 'admin/reported' => 'admin#reported'
  match 'admin/newsletter' => 'admin#newsletter'

  resources :starship_configurations
  resources :starship_configuration_items
  resources :units
  resources :armies
  resources :starships
  resources :starship_types
  resources :buildings
  resources :estates
  resources :characters
  resources :orders
  resources :messages
  resources :noble_houses
  resources :regions
  resources :items
  resources :worlds
  resources :building_types
  resources :player_sessions
  resources :players
  resources :image_files

end

app/controllers/noble_houses_controller.rb
class NobleHousesController < ApplicationController
  respond_to :html, :js
  
  before_filter :no_noble_house, :only => [:new, :create]

  def index
    unless cached?
      if params[:page].blank?
        if current_noble_house
          page = current_noble_house.page_number
          #Kernel.p "!!!!! CURRENT HOUSE PAGE FOR HOUSE = #{page} !!!!"
        else
          page = 1
        end
      else
        page = params[:page]
      end
      if params[:order] == 'glory_desc'
        list_order = "glory DESC"
      elsif params[:order] == 'glory_asc'
        list_order = "glory ASC"
      elsif params[:order] == 'honour_desc'
        list_order = "honour DESC"
      elsif params[:order] == 'honour_asc'
        list_order = "honour ASC"
      elsif params[:order] == 'piety_desc'
        list_order = "piety DESC"
      elsif params[:order] == 'piety_asc'
        list_order = "piety ASC"
      elsif params[:order] == 'name_desc'
        list_order = "name DESC"
      elsif params[:order] == 'name_asc'
        list_order = "name ASC"
      else
        list_order = "glory DESC, honour DESC, piety DESC, name ASC"
      end
      @noble_houses = NobleHouse.where('(ancient = 1 OR active = 1) AND baron_id IS NOT NULL AND baron_id <> 0').paginate(:page => page).order(list_order)
    end
  end

  def new
    @noble_house = NobleHouse.new
    @noble_house.setup_region
  end

  def create
    @noble_house = NobleHouse.new(params[:noble_house])
    @noble_house.update_attributes(:player => current_player, :wealth => NobleHouse::STARTING_CASH, :formed_date => Game.current_date)
    if @noble_house.save
      call_rake(:setup_house, @noble_house.signup_variables_hash)
      flash[:notice] = "Your new Noble House will be created shortly and you will be notified by email when it is ready for you to start playing. Thank you for your patience."
      current_player_session.destroy
      redirect_to root_url
    else
      render :action => 'new'
    end
  end

  def show
    begin
      if params[:name]
        @noble_house = NobleHouse.find_by_name(params[:name])
      elsif params[:id]
        @noble_house = NobleHouse.find(params[:id])
      else
        redirect_to :action => :index
        return
      end
      unless @noble_house && @noble_house.active?
        redirect_to :action => :index
      end
    rescue Exception => e
      # TODO logging
      Kernel.p "!!! RESCUE #{e.to_s}\n#{e.backtrace.join("\n")}"
      redirect_to :action => :index
    end
  end

  def no_noble_house
    unless current_player && current_noble_house.nil?
      redirect_to root_url
    end
  end

  def cache_model
    @noble_house || super
  end
end

app/helpers/noble_houses_helper.rb
module NobleHousesHelper
  def link_to_own_house
    return unless current_noble_house
    link_to "House #{current_noble_house.name}", "/House/#{current_noble_house.name}"
  end

  def noble_house_path(house)
    "/House/#{house.name}"
  end

  def link_to_house(house)
    return if house.nil?
    link_to "House #{house.name}", noble_house_path(house)
  end

  def options_for_houses(selected,include_ancient=true,exclude_own_house=true)
    if exclude_own_house
      list = include_ancient ? NobleHouse.active_or_ancient.exclude(current_noble_house).all(:order => 'name ASC') : NobleHouse.active.exclude(current_noble_house).all(:order => 'name ASC')
    else
      list = include_ancient ? NobleHouse.active_or_ancient.all(:order => 'name ASC') : NobleHouse.active.all(:order => 'name ASC')
    end
    id = selected.nil? ? 0 : selected.to_i
    options_from_collection_for_select(list,"id","name_with_ancient",id)
  end

  def house_wealth_description(noble_house)
    if noble_house.wealth <= 10000
      return "House #{noble_house.name} is considered <strong>impoverished</strong>.".html_safe
    elsif noble_house.wealth <= 100000
      return "House #{noble_house.name} is of <strong>modest means</strong>.".html_safe
    elsif noble_house.wealth <= 500000
      return "House #{noble_house.name} is substantially <strong>prosperous</strong>.".html_safe
    elsif noble_house.wealth <= 1000000
      return "House #{noble_house.name} is decadently <strong>affluent</strong>.".html_safe
    elsif noble_house.wealth <= 5000000
      return "House #{noble_house.name} is quite <strong>wealthy</strong>.".html_safe
    else
      return "House #{noble_house.name} is <strong>rich</strong> and flaunts its opulence.".html_safe
    end
  end
end

app/views/noble_houses/_form.html.erb
<%= form_for @noble_house, :html => { :multipart => true } do |f| %>
  <p><strong>Note:</strong> Items marked <span class="required">*</span> are required fields</p>
  <%= form_error_messages(@noble_house) %>
  <fieldset id="house">
  	<legend><span>Noble House</span></legend>
  	<ol>
  		<li>
  			<%= f.label :house_name, :class => 'required' %>
    		<%= f.text_field :name %>
        <br/><strong>Note:</strong> You don't need to include "House" in the name.
    	</li>
  	</ol>
  </fieldset>
  <% if @noble_house.new_record? %>
  <%=render :partial => 'new', :locals => {:f => f} %>
  <% end %>
  <fieldset id="submitform">
    <%= f.submit submit_text %>
  </fieldset>
<% end %>

app/views/noble_houses/_new.html.erb

<fieldset id="patriarch">
  <legend><span>House Patriarch</span></legend>
  <ol>
    <li>
      <%= f.label :patriarch_name, :class => 'required' %>
      <%= f.text_field :patriarch %>
      <br/><strong>Note:</strong> Your house name will automatically be used as the surname of your patriarch.
    </li>
    <li>
      <%= f.label 'Military Skill - Expert', :class => 'required' %>
      <%= f.select :patriarch_skill1, options_for_skills(@noble_house.patriarch_skill1, Skill::MILITARY_SKILLS), {:include_blank => true} %>
      <%= wiki_help('Skills#Skills') %>
    </li>
    <li>
      <%= f.label 'Civil Skill - Expert', :class => 'required' %>
      <%= f.select :patriarch_skill2, options_for_skills(@noble_house.patriarch_skill2, Skill::CIVIL_SKILLS), {:include_blank => true} %>
      <%= wiki_help('Skills#Skills') %>
    </li>
    <li>
      <%= f.label 'Civil Skill - Apprentice', :class => 'required' %>
      <%= f.select :patriarch_skill3, options_for_skills(@noble_house.patriarch_skill3, Skill::CIVIL_SKILLS), {:include_blank => true} %>
      <%= wiki_help('Skills#Skills') %>
    </li>
  </ol>
</fieldset>
<fieldset id="matriarch">
  <legend><span>House Matriarch</span></legend>
  <ol>
    <li>
      <%= f.label :matriarch_name, :class => 'required' %>
      <%= f.text_field :matriarch %>
      <br/><strong>Note:</strong> Your house name will automatically be used as the surname of your matriarch.
      </li>
    <li>
      <%= f.label 'Ecclesiastical Skill - Expert', :class => 'required' %>
      <%= f.select :matriarch_skill1, options_for_skills(@noble_house.matriarch_skill1, Skill::CHURCH_SKILLS), {:include_blank => true} %>
      <%= wiki_help('Skills#Skills') %>
    </li>
    <li>
      <%= f.label 'Civil Skill - Apprentice', :class => 'required' %>
      <%= f.select :matriarch_skill2, options_for_skills(@noble_house.matriarch_skill2, Skill::CIVIL_SKILLS), {:include_blank => true} %>
      <%= wiki_help('Skills#Skills') %>
    </li>
    <li>
      <%= f.label 'Civil Skill - Apprentice', :class => 'required' %>
      <%= f.select :matriarch_skill3, options_for_skills(@noble_house.matriarch_skill3, Skill::CIVIL_SKILLS), {:include_blank => true} %>
      <%= wiki_help('Skills#Skills') %>
    </li>
  </ol>
</fieldset>
<fieldset id="children">
  <legend><span>Adult Children</span></legend>
  <ol>
    <li>
      <%= f.label :first_child_name, :class => 'required' %>
      <%= f.text_field :first_child_name %> (male)
    </li>
    <li>
      <%= f.label :skill, :class => 'required' %>
      <%= f.select :first_child_skill, options_for_skills(@noble_house.first_child_skill), {:include_blank => true} %>
      <%= wiki_help('Skills#Skills') %>
    </li>
    <li>
      <%= f.label :second_child_name, :class => 'required' %>
      <%= f.text_field :second_child_name %> (male)
    </li>
    <li>
      <%= f.label :skill, :class => 'required' %>
      <%= f.select :second_child_skill, options_for_skills(@noble_house.second_child_skill), {:include_blank => true} %>
      <%= wiki_help('Skills#Skills') %>
    </li>
    <li>
      <%= f.label :third_child_name, :class => 'required' %>
      <%= f.text_field :third_child_name %> (female)
    </li>
    <li>
      <%= f.label :skill, :class => 'required' %>
      <%= f.select :third_child_skill, options_for_skills(@noble_house.third_child_skill), {:include_blank => true} %>
      <%= wiki_help('Skills#Skills') %>
    </li>
    <li>
      <strong>Note:</strong> Your house name will automatically be used as the surname of your characters.
    </li>
  </ol>
</fieldset>
<fieldset id="estate">
  <legend><span>Home Estate</span></legend>
  <ol>
    <li>
      <%= f.label :estate_name, :class => 'required' %>
      <%= f.text_field :estate_name %>
      <br/><strong>Note:</strong> You don't need to include "Estate" as part of the name.
    </li>
    <li>
      <%= f.label :region, :class => 'required' %>
      <%= f.select :region, options_for_regions(@noble_house.region,nil,true) %>
    </li>
  </ol>
</fieldset>

app/views/noble_houses/_new_house_help.html.erb
<fieldset>
	<legend>Some Hints on Starting Skills</legend>
	<ol>
		<li>
			Its recommended you choose skills for each character that will help them in a specific role.
			<br/>You are free to disregard these recommendations if you have a plan of your own.
		</li>
		<li>
			Your <strong>Patriarch</strong> as the Baron of your house is your most important character. You can set him up to fulfill a number of roles at different times.
			<br/><strong>Tournaments / Trial By Combat</strong>: Melee (swords), Etiquette (lances)
			<br/><strong>Estate Management</strong>: Engineering (cheaper construction), Management (more efficient buildings), Barter (cheaper land purchases), Organisation (less workers needed)
			<br/><strong>Leading Armies</strong>: Leadership (improved morale), Tactics (better tactical phase), Fortification (better defenses), Explosive (better at destroying bunkers), Logistics (quicker army movement)
		</li>
		<li>
			Your <strong>Matriarch</strong> is your second most important character and can be set up to do multiple roles well. Note: The best skill between Lord and Steward is used.
			<br/><strong>Steward of Estate</strong>: Engineering (cheaper construction), Management (more efficient buildings), Organisation (less workers needed), Automation (more ore production), Biogenics (more trade good production).
			<br/><strong>Diplomat / Spy</strong>: Research (for spying), Diplomacy (for petitions), Apothecary (for assassinations).
			<br/><strong>Other useful skills</strong>: Medicine (heal sick or injured), Etiquette (host events)
		</li>
		<li>
			Other characters should be skilled to do a needed job.
			<br/><strong>Tribune</strong>: Recruitment.
			<br/><strong>Chancellor</strong>: Administration.
			<br/><strong>Warship Captain</strong>: Piloting (better dodge), Shooting (better accuracy), Electronics (better shields), Damage Control (less chance of losing internals due to hull damage).
			<br/><strong>Freighter Captain</strong>: Navigation (faster movement).
			<br/><strong>Legate</strong>: Leadership (better morale), Tactics (better tactical phase), Explosives (better against bunkers), Logistics (faster army movement)
			<br/><strong>Emissaries</strong>: Diplomacy (better petitions), Research (better spying), Explosives (better sabotage), Apothecary (better assassinations).
		</li>
		<li>
			You're not restricted to these choices and every skill has its uses.
		</li>
	</ol>
</fieldset>

app/views/noble_houses/_tabs.html.erb
<%=tab(:overview, true) do -%>
<div id="overview" class="tab">
  <%=wiki_help_div('Noble_Houses', 'Noble Houses')%>
  <div class="message-toolbar">
  <% unless @noble_house.ancient? || !current_player || !current_baron || current_baron.id == @noble_house.baron_id %>
  <%= link_to(image_tag('new_message.png',:title => 'Send a message', :alt => 'Send a message', :width => 32, :height => 32), "#{new_message_path}?baron=#{@noble_house.baron.guid}") %>
  <% end %>
  </div>

  <% unless @noble_house.baron.nil? %>
  <p>
    <%=link_to_character @noble_house.baron, :name_and_family %> is the sovereign of this house. It was formed on the <%=h @noble_house.formed_date.to_pretty %>.
  </p>
  <% end %>
  <% if @noble_house.home_estate %>
    <p>Its home estate is <%=link_to_estate @noble_house.home_estate %> in <%=link_to_region(@noble_house.home_estate.region)%> on <%=link_to_world(@noble_house.home_estate.region.world)%>.</p>
  <% end %>
  <p>
  <% if @noble_house.chancellor %>
    <%=link_to_character @noble_house.chancellor, :name_and_family %> is the current Chancellor.<br/>
  <% elsif belongs_to_current_player?(@noble_house) %>
    <span class="warning">A Chancellor needs to be appointed to automatically collect taxes from all estates each year.</span>
  <% end %>
  </p>
  <p>
    <%=house_wealth_description(@noble_house)%>
  </p>
  <p>
    Its honour with the houses is <%=h @noble_house.honour.to_i %> whilst its glory is <%=h @noble_house.glory.to_i %>. The Church states it has <%=h @noble_house.piety.to_i %> piety.
  </p>
  <%=render :partial => '/diplomatic_relations/list', :locals => {:noble_house => @noble_house} %>
</div>
<% end -%>

<%=tab(:members) do -%>
<div id="members" class="tab">
  <%=wiki_help_div('Characters')%>
  <%=render :partial => '/characters/list', :locals => {:characters => Character.of_house(@noble_house).living} %>
</div>
<% end -%>

<%=tab(:deceased) do -%>
<div id="members" class="tab">
  <%=wiki_help_div('Characters')%>
  <%=render :partial => '/characters/deceased', :locals => {:characters => Character.of_house(@noble_house).dead} %>
</div>
<% end -%>

<%= tab(:authorisations) do -%>
  <div id="authorisations" class="tab">
    <%= render :partial => '/authorisations/list', :locals => {:authorisations => @noble_house.authorisations, :show_estate => true } %>
  </div>
<% end -%>


<%=tab(:news) do -%>
<div id="news" class="tab">
  <%=render :partial => '/news/list', :locals => {:news => @noble_house.news_log(current_noble_house), :highlight_public_news => (current_noble_house && current_noble_house.id == @noble_house.id)} %>
</div>
<% end -%>

app/views/noble_houses/_toolbar.erb
<%
if belongs_to_current_player?(@noble_house)
  unless toolbar_cached? || !@noble_house.baron.can_be_given_orders?
    quick_orders = []
    quick_orders << 'Appoint Chancellor' unless @noble_house.chancellor
    quick_orders << 'Claim Title'
    if @noble_house.has_truce_offers?
      quick_orders << 'Accept Truce'
      quick_orders << 'Reject Truce'
    end
    if @noble_house.has_peace_offers?
      quick_orders << 'Accept Peace'
      quick_orders << 'Reject Peace'
    end
    if @noble_house.has_alliance_offers?
      quick_orders << 'Accept Alliance'
      quick_orders << 'Reject Alliance'
    end
    if @noble_house.has_oath_offers?
      quick_orders << 'Accept Allegiance'
      quick_orders << 'Reject Allegiance'
    end
    quick_orders << 'Break Oath' if @noble_house.has_oath?
    quick_orders << 'Break Alliance' if @noble_house.has_allies?
    quick_orders << 'Ransom Prisoner' if @noble_house.imprisoned_members.size > 0

    quick_orders << 'Demand Justice'

    order_toolbar(@noble_house.baron, quick_orders) unless quick_orders.empty?

    if @noble_house.chancellor
      order_toolbar(@noble_house.chancellor,['Set Tax Level'])
    end
  end
end
%>

app/views/noble_houses/index.html.erb
<% title "Noble Houses of the Empire" %>

<%=tab(:index, true, false) do-%>
  <table cellspacing="4" cellpadding="4">
    <tr>
      <th><%=sortable_table_head('House','name')%></th>
      <th>Baron</th>
      <th>Members</th>
      <th><%=sortable_table_head('Honour','honour')%></th>
      <th><%=sortable_table_head('Glory','glory')%></th>
      <th><%=sortable_table_head('Piety','piety')%></th>
      <th>Formed Date</th>
    </tr>
    <% for noble_house in @noble_houses 
      if current_noble_house && noble_house.id == current_noble_house.id
        css_class = 'selected_row'
      else
        css_class = ''
      end
    %>
      <tr>
        <td class="<%=css_class%>"><%=link_to_house noble_house %></td>
        <td class="<%=css_class%>"><%=link_to_character noble_house.baron, :short_display_name %></td>
        <td class="<%=css_class%>"><%=h Character.count_living(noble_house) %></td>
        <td class="<%=css_class%>"><%=h noble_house.honour.to_i %></td>
        <td class="<%=css_class%>"><%=h noble_house.glory.to_i %></td>
        <td class="<%=css_class%>"><%=h noble_house.piety.to_i %></td>
        <td class="<%=css_class%>"><%=h noble_house.formed_date.to_pretty %></td>
      </tr>
    <% end %>
  </table>
  <div class="pagination">
    <%= will_paginate @noble_houses %>
  </div>
<% end -%>

app/views/noble_houses/new.html.erb
<% title "Form A New Noble House" %>

<div id="new-house" class="tab">
<table class="no_style">
	<tr>
		<td style="width: 50%;">
			<%= render :partial => 'form', :locals => {:submit_text => 'Complete Sign Up'} %>
		</td>
		<td style="width: 50%; vertical-align: top; padding-top: 60px;">
			<%= render :partial => 'new_house_help' %>
		</td>
	</tr>
</table>
</div>

app/views/noble_houses/show.html.erb
<% title "House #{@noble_house.name}" %>
<% 
if belongs_to_current_player?(@noble_house)
  render :partial => 'toolbar'
  character_orders_tabs = []
  character_orders_tabs << link_to("Baron Orders","#{character_path(@noble_house.baron)}?tab=orders")
  character_orders_tabs << link_to("Chancellor Orders","#{character_path(@noble_house.chancellor)}?tab=orders") if @noble_house.chancellor
  tabbed_menu({:overview => 'Overview', :news => "House #{@noble_house.name} News", :members => 'Members', :deceased => 'Lest We Forget', :authorisations => 'Authorisations'},[link_to("Estates", estates_path),link_to("Armies", armies_path),link_to("Starships", starships_path)] + character_orders_tabs)
else
  tabbed_menu({:overview => 'Overview', :news => "House #{@noble_house.name} News", :members => 'Members', :deceased => 'Lest We Forget'})
end
%>

<%=render :partial => 'tabs' %>

app/views/noble_houses/show.js.erb
<% render :partial => 'toolbar' %>
<%=js_tab(render :partial => 'tabs')%>