config/routes.rb
Throneofthestars::Application.routes.draw do

  match '' => 'home#index', :as => :root
  match 'empire' => 'empire#index', :as => :empire
  match 'church' => 'church#index', :as => :church
  match 'announcements' => 'empire#announcements', :as => :announcements
  match 'login' => 'player_sessions#new', :as => :login
  match 'logout' => 'player_sessions#destroy', :as => :logout
  match 'password_reset' => 'password_resets#new', :as => :password_reset
  match 'password_reset/:id' => 'password_resets#edit', :as => :edit_password
  match 'confirm/:id' => 'players#confirm', :as => :confirm
  match 'House/:name' => 'noble_houses#show'
  match 'Planet/:name' => 'worlds#show'
  match 'Planet/:world/:name' => 'regions#show'
  match 'Item/:name' => 'items#show'
  match 'BuildingType/:name' => 'building_types#show'
  match 'ShipType/:name' => 'starship_types#show'
  match 'Character/:guid' => 'characters#show'
  match 'Starship/:guid' => 'starships#show'
  match 'Army/:guid' => 'armies#show'
  match 'Army/:guid/units/:id' => 'units#show'
  match 'Army/:guid/units/:id/edit' => 'units#edit'
  match 'Estate/:guid' => 'estates#show'
  match 'Character/:guid/promote' => 'characters#promote'
  match 'json/world_regions/:id' => 'json#world_regions'
  match 'json/region_estates/:id' => 'json#region_estates'
  match 'json/house_characters/:id' => 'json#house_characters'
  match 'json/single_females/:id' => 'json#single_females'
  match 'json/single_males/:id' => 'json#single_males'
  match 'json/army_units/:id' => 'json#army_units'
  match 'messages/preview' => 'messages#preview'
  match 'Message/:guid' => 'messages#show'
  match 'unsubscribe/:guid' => 'players#unsubscribe'
  match 'orders/:id/up' => 'orders#up'
  match 'orders/:id/down' => 'orders#down'
  match 'orders/:id/cancel' => 'orders#destroy'
  match 'admin' => 'admin#index'
  match 'admin/players' => 'admin#players'
  match 'admin/spawner' => 'admin#spawner'
  match 'admin/reported' => 'admin#reported'
  match 'admin/newsletter' => 'admin#newsletter'

  resources :starship_configurations
  resources :starship_configuration_items
  resources :units
  resources :armies
  resources :starships
  resources :starship_types
  resources :buildings
  resources :estates
  resources :characters
  resources :orders
  resources :messages
  resources :noble_houses
  resources :regions
  resources :items
  resources :worlds
  resources :building_types
  resources :player_sessions
  resources :players
  resources :image_files

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :name, :army, :knight
  
  after_save  :calculate_army_movement

  MAX_UNIT_MASS = 10000
  validates_presence_of :name
  belongs_to :army
  belongs_to :knight, :class_name => 'Character'

  scope :of_house, lambda {|house|
    {:conditions => ["army_id IN (?)", house.armies]}
  }

  scope :of, lambda {|army|
    {:conditions => {:army_id => army.id}}
  }

  scope :by_id, lambda {|id|
    {:conditions => {:id => id}}
  }

  include ItemContainer

  def assign_knight!(character)
    return false unless character && character.knight? && self.knight.nil?
    self.knight = character
    save!
    self.army.add_news!('LEAD_UNIT',"#{self.name} is being led by #{character.display_name}")
    character.join_unit!(self)
    true
  end

  def category_allowed?(category)
    return false unless Item::MILITARY.include?(category)
    return true if empty?
    return true if total_aircraft > 0 && category == Item::AIRCRAFT
    return true if total_ordinance > 0 && category == Item::ORDINANCE
    true
  end

  def space_available(category)
    if category_allowed?(category)
      MAX_UNIT_MASS
    else
      0
    end
  end

  def total_troops
    @total_troops ||= sum_category_quantity(Item::TROOP)
  end

  def total_aircraft
    @total_aircraft ||= sum_category_quantity(Item::AIRCRAFT)
  end

  def total_tanks
    @total_tanks ||= sum_category_quantity(Item::TANK)
  end

  def total_ordinance
    @total_ordinance ||= sum_category_quantity(Item::ORDINANCE)
  end

  def total_transports
    @total_transports ||= sum_category_quantity(Item::TRANSPORT)
  end

  def transport_capacity
    @transport_capacity ||= sum_item_attributes(:transport_capacity)
  end

  def transport_required
    @transport_required ||= sum_qualified_item_attributes(:ground_movement_only?, :mass)
  end

  def ground?
    @ground ||= distinct_item_attributes(:movement).include?(Item::MOVEMENT_GROUND)
  end

  def air?
    @air ||= orbit? || transported_movement?(Item::MOVEMENT_AIR)
  end

  def orbit?
    @orbit ||= transported_movement?(Item::MOVEMENT_ORBIT)
  end

  def movement_types
    @movement_types ||= calculate_movement_types
  end

  def calculate_army_movement
    self.army.calculate_movement_type
  end

  private
  def transported_movement?(movement_type)
    distinct_item_attributes(:movement).include?(movement_type) && transport_required <= transport_capacity
  end

  def calculate_movement_types
    list = []
    list << "Ground" if ground?
    list << "Air" if air?
    list << "Orbital" if orbit?
    list
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_filter :require_noble_house
  
  def show
    @unit = Unit.find(params[:id])
    return if redirect_if_unauthorized(@unit.army)
    update if params[:unit]
  end

  def update
    @unit = Unit.find(params[:id])
    return if redirect_if_unauthorized(@unit.army)
    old_name = @unit.name
    if @unit.update_attributes(:name => params[:unit][:name])
      flash[:notice] = "Unit #{old_name} is now called #{@unit.name}"
      redirect_to unit_path(@unit)
    else
      flash[:error] = "Failed to update unit name."
      redirect_to unit_path(@unit)
    end
  end

  def cache_model
    @unit || super
  end
end

app/helpers/units_helper.rb
module UnitsHelper
  def link_to_unit(unit)
    link_to unit.name, unit unless unit.nil?
  end

  def options_for_units(selected,army)
    list = army.nil? ? [] : Unit.of(army)
    id = selected.nil? ? 0 : selected.to_i
    options_from_collection_for_select(list,"id","name",id)
  end
end

app/views/units/_form.html.erb
<%= form_for @unit do |f| %>
  <%= form_error_messages(@unit) %>
  <fieldset id="name">
    <legend><span>Change Name</span></legend>
  <ol>
    <li>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </li>
  </ol>
  </fieldset>
  <fieldset id="submitform">
    <%= f.submit "Rename Unit" %>
  </fieldset>
<% end %>

app/views/units/_tabs.html.erb
<%=tab(:composition, true) do -%>
<div id="composition" class="tab">
	<p>A unit of the <%=link_to_army(@unit.army)%>.</p>
	<% if @unit.knight %>
	<p>
	  <strong>Knight:</strong>
	  <%=link_to_character @unit.knight %>
	</p>
	<% end %>
	<%=render :partial => '/items/bundles', :locals => {:items => @unit.bundles} %>
</div>
<% end -%>

<%=tab(:edit,false,false) do -%>
<div id="edit" class="tab">
	<%=render :partial => 'form'%>
</tab>
<% end -%>

app/views/units/_toolbar.erb
<%
  unless toolbar_cached?
    quick_orders = []
    if @unit.army.legate
      if tab?(:composition) || no_tab?
        quick_orders << 'Load Unit'
        quick_orders << 'Unload Unit'
      end
    end
    order_toolbar(@unit.army.legate, quick_orders, @unit) unless quick_orders.empty?
  end
%>

app/views/units/show.html.erb
<% title "Unit #{@unit.name}" %>
<% 
render :partial => 'toolbar'
tabbed_menu({:unit => 'Composition', :edit => 'Change Name'},[link_to("Army #{@unit.army.name}", @unit.army),link_to('Other Units',"#{army_path(@unit.army)}?tab=units")]) %>

<%=render :partial => 'tabs'%>

app/views/units/show.js.erb
<% render :partial => 'toolbar' %>
<%=js_tab(render :partial => 'tabs')%>